#!/bin/bash

rm ./winners.txt
touch ./winners.txt

for i in `seq 1000 2000`; do
  ./main.byte "tests/game.json" $i | grep 'won' >> ./winners.txt
done

for var in "$@"
do
    printf "$var : " && grep -c $var ./winners.txt
done

printf "Total : " && grep -c "" ./winners.txt
