#!/bin/bash

rm ./winners.txt
touch ./winners.txt

for i in `seq 1000 2000`; do
  ./main.byte "tests/game.json" $i | grep 'won' >> ./winners.txt
done

grep -c $1 ./winners.txt && printf "/" && grep -c "" ./winners.txt
